### ISSUE TITLE
Population of partition index too Expensive

### ISSUE THREAD

**Issue by Elbehery** [alitouka/spark_dbscan#10]
@alitouka  

I am running the algorithm on a machine with 64G RAM, 16 CPUs . I have 500 MB of data, which is relatively small. However, The algorithm always spend so much time, in **Population of partition index** step. 

Do u have any suggestion regarding this ?

**Comment by speedymrk9** [comment]
How many dimensions do your data have?

**Comment by Elbehery** [comment]
Only two, Latitude & Langtitude
